global using System.Collections.Immutable;
global using System.Text;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Testing;
global using Microsoft.CodeAnalysis.Testing.Verifiers;
global using Microsoft.CodeAnalysis.Text;
global using Microsoft.Extensions.ObjectPool;
global using Xunit;
